# 所有环境通用的配置，放在这里
spring:
  application:
    name: shuai-user
  profiles:
    active: dev
# 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#配置内嵌容器tomcat的监听端口和上下文路径
server:
  port: 9090
  context-path:
  ssl:
    enabled: false
management:
  security:
    enabled: false

logging:
  level: info
    org:
      springframework:
        security:
          web:
            authentication: error
  file: /logs/${spring.application.name}.log
endpoints:
  logfile:
    enabled: true

provider:
  group: zc-sso-${spring.profiles}

swaggerVersion: 1.0

#mybatis:
#  config-location: config/mybatis-config.xml

#mapper:
#    mappers:
#        - com.zcckj.storeshow.common.BaseMapper
#    not-empty: false
#    identity: MYSQL
#pagehelper
pagehelper:
  #当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: false
  #当该参数设置为true时，使用 RowBounds 分页会进行 count 查询
  rowBoundsWithCount: true

staticPath: classpath:/