# 所有环境通用的配置，放在这里
spring:
  profiles:
    active: dev
# 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#配置内嵌容器tomcat的监听端口和上下文路径
server:
  port: 9090
  context-path:
  ssl:
    enabled: false
management:
  security:
    enabled: false